# Generated by Django 2.2.7 on 2019-11-15 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunMitra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('provinsi', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='mitra/poto_profil/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iklan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='mitra/iklan/%Y/%m/%d/')),
                ('judul', models.CharField(max_length=150)),
                ('published', models.DateField(auto_now_add=True)),
                ('jenis_kendaraan', models.CharField(max_length=20)),
                ('merk', models.CharField(max_length=30)),
                ('tipe_kendaraan', models.CharField(max_length=30)),
                ('harga_sewa', models.IntegerField()),
                ('deskripsi_lain', models.TextField()),
                ('slug', models.SlugField()),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitra.AkunMitra')),
            ],
        ),
    ]
