# Generated by Django 2.2.7 on 2019-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akunmitra',
            name='provinsi',
            field=models.CharField(choices=[('Aceh', 'aceh'), ('Bali', 'bali'), ('Banten', 'banten'), ('Bengkulu', 'bengkulu'), ('Gorontalo', 'gorontalo'), ('D.I Yogyakarta', 'yogyakarta'), ('D.K.I Jakarta', 'jakarta'), ('Jambi', 'jambi'), ('Jawa Barat', 'jawa_barat'), ('Jawa Tengah', 'jawa_tengah'), ('Jawa Timur', 'jawa_timur'), ('Kalimantan Barat', 'kalimantan_barat'), ('Kalimantan Selatan', 'kalimantan_selatan'), ('Kalimantan Tengah', 'kalimantan_tengah'), ('Kalimantan Timur', 'kalimantan_timur'), ('Kalimantan Utara', 'kalimantan_utara'), ('Kep. Bangka Belitung', 'bangka_belitung'), ('Kep. Riau', 'kepri'), ('Lampung', 'lampung'), ('Maluku', 'maluku'), ('Maluku Utara', 'maluku_utara'), ('Nusa Tenggara Barat', 'nusa_tenggara_barat'), ('Nusa Tenggara Timur', 'nusa_tenggara_timur'), ('Papua', 'papua'), ('Papua Barat', 'papua_barat'), ('Riau', 'riau'), ('Sulawesi Barat', 'sulawesi_barat'), ('Sulawesi Selatan', 'sulawesi_selatan'), ('Sulawesi Tengah', 'sulawesi_tengah'), ('Sulawesi Tenggara', 'sulawesi_tenggara'), ('Sulawesi Utara', 'sulawesi_utara'), ('Sumatera Barat', 'sumatera_barat'), ('Sumatera Selatan', 'sumatera_selatan'), ('Sumatera Utara', 'sumatera_utara')], max_length=50),
        ),
    ]
