# Generated by Django 2.2.7 on 2019-11-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitra', '0003_auto_20191116_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iklan',
            name='harga_sewa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
