# Generated by Django 2.2.7 on 2019-11-19 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitra', '0005_auto_20191119_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iklan',
            name='mitra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
