# Generated by Django 2.2.7 on 2019-11-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitra', '0006_auto_20191119_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iklan',
            name='harga_sewa',
            field=models.CharField(max_length=50),
        ),
    ]
